# Generated by Django 3.0.8 on 2020-07-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.URLField(max_length=255)),
                ('amazon_link', models.URLField(max_length=255)),
                ('description', models.TextField()),
                ('book_type', models.CharField(max_length=255)),
                ('book_genre', models.CharField(max_length=255)),
                ('book_length', models.CharField(max_length=255)),
                ('publish_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_author', models.BooleanField(default=False)),
                ('is_critic', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(to='core.Book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(limit_choices_to={'is_author': True}, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='core.Person'),
        ),
        migrations.AddField(
            model_name='book',
            name='recommender',
            field=models.ForeignKey(limit_choices_to={'is_critic': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recommender', to='core.Person'),
        ),
    ]
