# Generated by Django 3.0.8 on 2020-07-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
